'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const ui=fs.readFileSync('gemini-draft-ui.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
assert.match(ui,/data-upload-progress/);
assert.match(ui,/x\.upload\.onprogress/);
assert.match(ui,/Math\.round\(100\*e\.loaded\/e\.total\)/);
assert.match(ui,/progress\('Foto enviada\. Make\/Gemini processando…',null\)/,'processing must be indeterminate, never fabricated percent');
assert.match(ui,/data-gemini-json/);
assert.match(ui,/<details class="rlt-technical-backup">/);
assert.match(ui,/data-json-copy/);
assert.match(ui,/data-json-download/);
assert.match(ui,/details\.insertBefore\(human,technicalTables\)/,'human review first');
assert.match(ui,/data-correct-confirm/);
assert.match(ui,/data-review-transfer/);
assert.match(ui,/rlt-five-column-table/);
assert.match(ui,/<th>Nº Escolhido<\/th><th>Nº Sorteado<\/th><th>Corretor<\/th><th>Classe<\/th><th>Check<\/th>/);
for(const required of ['data-correct-class','value="standby"','value="online"','value="excluir"','data-correct-confirm'])assert.ok(ui.includes(required),required);
assert.doesNotMatch(ui,/rlt-operational-scroll/);
assert.match(css,/rlt-five-column-review\{[^}]*overflow:visible/);
assert.match(css,/rlt-five-column-table\{[^}]*min-width:0/);
assert.doesNotMatch(css,/rlt-operational-table/);
assert.match(css,/input\[data-correct-position\]/);
assert.match(css,/input\[data-correct-number\]/);
assert.match(css,/rlt-five-column-table th:nth-child\(4\)/);
assert.match(css,/rlt-five-column-table th:nth-child\(5\)/);
console.log('PASS mobile backfill progress, technical backup, canonical transfer and compact review guards');
