'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const ui=fs.readFileSync('gemini-draft-ui.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
assert.match(ui,/data-upload-progress/);
assert.match(ui,/x\.upload\.onprogress/);
assert.match(ui,/Math\.round\(100\*e\.loaded\/e\.total\)/);
assert.match(ui,/progress\('Foto enviada\. Make\/Gemini processando…',null\)/,'processing must be indeterminate, never fabricated percent');
assert.match(ui,/data-gemini-json/);
assert.match(ui,/<details class="rlt-technical-backup">/);
assert.match(ui,/data-json-copy/);
assert.match(ui,/data-json-download/);
assert.match(ui,/details\.insertBefore\(human,technicalTables\)/,'human review first');
assert.match(ui,/data-correct-confirm/);
assert.match(ui,/data-review-transfer/);
assert.match(ui,/rlt-operational-table/);
assert.match(css,/rlt-operational-scroll\{[^}]*overflow-x:auto/);
assert.match(css,/input\[data-correct-position\]/);
assert.match(css,/input\[data-correct-number\]/);
assert.match(css,/left:108px/);
console.log('PASS mobile backfill progress, technical backup, canonical transfer and compact review guards');
