const assert=require('node:assert/strict');
const {convertGeminiDraft}=require('../gemini-intake-converter.js');
const dto={brokers:[{nome:'Paola',creci:'123-F',gerente:'Wislane',diretor:'Renan',status_creci:'Definitivo'},{nome:'Nair',creci:'456-F',gerente:'Cazarim',diretor:'Renan',status_creci:'Definitivo'}]};
const src={empreendimento:'CAMINHOS DA LAPA',data:'08/10/2026',periodo:'TARDE',quantidade_corretores:2,linhas:[{posicao_impressa:1,nome_lido:'Nair',numero_sorteado:'02',gerente:'ERRADO'},{posicao_impressa:2,nome_lido:'Paola',numero_sorteado:'01'}]};
const ok=convertGeminiDraft(src,dto);
assert.equal(ok.payload.schema,'rlt-print-v2');
assert.equal(ok.payload.data,'2026-10-08');
assert.equal(ok.payload.salao[0].ordem_final,2);
assert.equal(ok.payload.salao[0].gerente,'Cazarim');
assert.equal(ok.payload.resultado.numero_exposto,false);
assert.equal(ok.status,'PENDENTE_REVISAO');
assert.equal(ok.impressao_liberada,false);
assert.equal(ok.payload.helbor_qtd,null);
const bad=convertGeminiDraft({...src,quantidade_corretores:17,linhas:[...src.linhas,{posicao_impressa:3,nome_lido:'Desconhecido',numero_sorteado:null}]},dto);
assert.ok(bad.pendencias.some(p=>p.code==='NOME_NAO_RESOLVIDO'));
assert.ok(bad.pendencias.some(p=>p.code==='ORDEM_INCOMPLETA'));
assert.ok(bad.pendencias.some(p=>p.code==='QUANTIDADE_CONFLITANTE'));
assert.equal(bad.payload.salao[0].ordem_final,null);
assert.throws(()=>convertGeminiDraft({},dto));
console.log('PASS: converter safety assertions');