const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const read=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
const css=read('styles.css'),js=read('roulette-intake.js');
assert.match(css,/body\s*>\s*:not\(#rltv2PrintHost\)\s*\{display:none!important\}/,'Non-print workspace must not consume paper');
assert.match(css,/#rltv2PrintHost\s*\{[\s\S]*?position:static!important/,'Canonical sheet must flow from top of page');
assert.match(js,/document\.body\.appendChild\(printHost\)/,'Print host must detach from workspace');
assert.match(js,/window\.addEventListener\('afterprint',restorePrintHost\)/,'Print must restore host after dialog');
assert.match(js,/printHost\.hidden=true/,'Host must be hidden once dialog closes');
assert.match(js,/print\.addEventListener\('click',openPrintDialog\)/);
assert.match(js,/savePdf\.addEventListener\('click',saveReadyPdf\)/);
assert.match(js,/sharePdf\.addEventListener\('click',shareReadyPdf\)/);
console.log('PASS: print-only layout, cleanup and separate print, PDF and share handlers');