'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const ui=fs.readFileSync('roulette-intake.js','utf8');
const print=ui.slice(ui.indexOf('function openPrintDialog()'),ui.indexOf("print.addEventListener('click',openPrintDialog)"));
assert.match(print,/URL\.createObjectURL\(pdfBlob\)/);
assert.match(print,/window\.open\(url,'_blank'\)/);
assert.doesNotMatch(print,/window\.print\(\)/);
assert.match(ui,/savePdf\.addEventListener\('click',saveReadyPdf\)/);
assert.match(ui,/sharePdf\.addEventListener\('click',shareReadyPhoto\)/);
assert.match(ui,/const file=new File\(\[photoBlob\]/);
assert.match(ui,/const url=URL\.createObjectURL\(pdfBlob\)/);
assert.match(ui,/print\.disabled=false;/);
console.log('PASS: print/save preserve PDF and share uses its rendered photo');
