(function(global){
  'use strict';
  function pageHead(eyebrow,title,desc){const h=document.createElement('div');h.className='workspace-page-head';h.innerHTML='<div><span class="eyebrow">'+eyebrow+'</span><h2>'+title+'</h2><p>'+desc+'</p></div>';return h}
  function familyCard(stats){
    const card=document.createElement('article');card.className='card workspace-family-module';
    card.innerHTML='<div class="section-head"><div><span class="eyebrow">RESULTADOS DA FAMÍLIA</span><h2>Números especiais</h2></div><span class="muted">'+stats.validated_events+' roletas nominais validadas</span></div><div class="workspace-family-grid">'+stats.family.map(x=>'<div class="workspace-family-card"><div class="workspace-family-name">'+x.display_name+'</div><div class="workspace-family-exp">'+x.participations+' participações</div><div class="workspace-family-stats"><div><span>Nº1</span><b>'+x.number1+'</b></div><div><span>Nº2</span><b>'+x.number2+'</b></div><div><span>Cortesia</span><b>'+x.courtesy+'</b></div><div><span>Último</span><b>'+x.last+'</b></div></div><div class="workspace-family-total">Total especial: <b>'+x.total_special+'</b></div></div>').join('')+'</div><p class="small muted workspace-data-note">Derivado do ledger nominal validado + transcrições canônicas; identidades pendentes ficam fora até confirmação.</p>';return card
  }
  function topCard(stats){
    const labels={number1:'Nº 1',number2:'Nº 2',courtesy:'Cortesia',last:'Último'},card=document.createElement('article');card.className='card workspace-top5-module';
    card.innerHTML='<div class="section-head"><div><span class="eyebrow">TOP 5 CORRETORES</span><h2>Nº1, Nº2, Cortesia e Último</h2></div><span class="muted">ledger nominal validado</span></div><div class="workspace-top5-grid">'+Object.entries(stats.top5).map(([key,rows])=>'<div class="workspace-top5-card"><div class="workspace-top5-title">'+labels[key]+'</div>'+rows.map((r,i)=>'<div class="workspace-top5-row"><span>'+(i+1)+'º</span><strong>'+r.broker+'</strong><em><b>'+r.hits+'</b> / '+r.participations+'</em></div>').join('')+'</div>').join('')+'</div>';return card
  }
  function recentSpecials(stats){
    const card=document.createElement('article');card.className='card workspace-recent-specials';const labels={number1:'Nº1',number2:'Nº2',courtesy:'Cortesia',last:'Último de vez'};
    card.innerHTML='<div class="section-head"><div><span class="eyebrow">ÚLTIMAS 2 ROLETAS</span><h2>Quem tirou os números especiais</h2></div><span class="muted">Nº1 · Nº2 · Cortesia · Último de vez</span></div><div class="recent-special-events">'+(stats.recentSpecials||[]).map(e=>'<section class="recent-special-event"><div class="recent-special-head"><div><strong>'+e.date+'</strong><span>'+e.period+' · N='+e.N+'</span></div><small>'+e.id+'</small></div><div class="recent-special-grid">'+Object.entries(e.specials).map(([k,b])=>'<div class="recent-special-item"><span>'+labels[k]+'</span><strong>'+(b?.name||'—')+'</strong><small>'+(b?'posição física '+b.position:'identidade indisponível')+'</small></div>').join('')+'</div></section>').join('')+'</div><p class="small muted workspace-data-note">Quadro de recência independente. Não altera o ranking histórico.</p>';return card
  }
  function renderWeekendStatus(x){
    const text=x.unresolved?'CONTAGEM A RECONCILIAR':(x.eligible?'APTO':('PENDENTE · FALTA '+x.missing));
    return '<div class="family-card '+(x.role==='principal'?'primary':'secondary')+'"><div class="family-head"><div><div class="family-name">'+x.broker+'</div><div class="family-role">'+x.role+'</div></div><div class="family-role">posição '+x.physical_position+(x.fallback_position?' · reserva '+x.fallback_position:'')+'</div></div><div class="family-number">'+(x.count??'—')+'<span class="family-denom">/'+x.required+'</span></div><div class="eligibility"><span class="counter">'+(x.unresolved?'aguardando contagem exata':'períodos confirmados nesta semana')+'</span><span class="flag '+(x.eligible?'ok':'')+'">'+text+'</span></div></div>'
  }
  function assignment(x,mode){return '<div class="assignment-card '+mode+'"><span class="assignment-name">'+x.broker+'</span><strong>'+x.physical_position+'</strong><span class="assignment-role">'+x.role+(x.fallback_position?' · reserva '+x.fallback_position:'')+'</span><span class="assignment-role '+(x.eligible?'pill-up':'pill-cold')+'">'+(x.count===null?'contagem pendente':(x.eligible?'APTO ':'PENDENTE ')+x.count+'/'+x.required)+'</span></div>'}
  async function mount(model){
    if(document.querySelector('.workspace-root'))return;
    const shell=document.querySelector('.shell');if(!shell)return;
    const root=document.createElement('div');root.className='workspace-root';shell.parentNode.insertBefore(root,shell);
    const sidebar=document.createElement('aside');sidebar.className='workspace-sidebar';sidebar.innerHTML='<div class="workspace-brand"><b>Roleta Intelligence</b><span>WORKSPACE V3</span></div><nav class="workspace-nav"><button class="active" data-workspace-page="overview">Visão geral</button><button data-workspace-page="intake">Nova Roleta</button><button data-workspace-page="family">Minha família</button><button data-workspace-page="ranking">Ranking</button><button data-workspace-page="weekend">Fim de semana</button><button data-workspace-page="models">Modelos & estatística</button><button data-workspace-page="simulation">Simulação</button></nav>';root.appendChild(sidebar);root.appendChild(shell);shell.classList.add('workspace-main');
    const names=['overview','intake','family','ranking','weekend','models','simulation'],pages={};for(const [i,n] of names.entries()){const p=document.createElement('section');p.id='workspace-'+n;p.className='workspace-page'+(i===0?' active':'');pages[n]=p}
    const first=shell.firstChild;for(const n of [...names].reverse())shell.insertBefore(pages[n],first);
    const move=(el,to)=>{if(el)to.appendChild(el)};move(shell.querySelector('.topbar'),pages.overview);move(shell.querySelector('.notice'),pages.overview);
    const prospective=document.createElement('article');prospective.id='prospectiveOverview';prospective.className='card workspace-prospective';prospective.innerHTML='<div class="section-head"><div><span class="eyebrow">RLT-M5-01 · PROSPECTIVO</span><h2>Pré-cravados da semana</h2></div></div><div class="muted small">Carregando ledger prospectivo…</div>';pages.overview.appendChild(prospective);
    const hero=shell.querySelector('.hero-grid');if(hero){const dup=hero.querySelector('.hero-card.accent');if(dup)dup.remove();hero.classList.add('workspace-hero','workspace-historical-signal');const intro=document.createElement('article');intro.className='card workspace-historical-intro';intro.innerHTML='<div class="section-head"><div><span class="eyebrow">SINAL HISTÓRICO · DESCRITIVO</span><h2>Leitura por período</h2></div><span class="historical-only-badge">NÃO PROSPECTIVO</span></div><p class="small muted">Estes números vêm do ranking histórico canônico e são apenas descritivos.</p>';pages.models.appendChild(intro);move(hero,pages.models)}
    move(shell.querySelector('.weekend-module'),pages.weekend);
    const dashboard=shell.querySelector('.dashboard-grid');if(dashboard){[...dashboard.children].forEach(card=>{if(card.querySelector('#rankingBars')||card.querySelector('#momentumList')||card.querySelector('#neverList'))move(card,pages.ranking);else if(card.querySelector('#previousDayEvents')||card.querySelector('#recentTimeline'))move(card,pages.overview);else if(card.querySelector('#modelCards')||card.querySelector('#modelLeaderboard')||card.querySelector('#viabilityState')||card.classList.contains('methodology'))move(card,pages.models)});if(!dashboard.children.length)dashboard.remove()}
    if(global.RouletteIntake)global.RouletteIntake.mount(pages.intake);else pages.intake.prepend(pageHead('NOVA ROLETA','Upload e validação','Módulo de entrada indisponível.'));
    pages.family.prepend(pageHead('MINHA FAMÍLIA','Histórico individual','Dados derivados fora da camada de apresentação.'));
    pages.ranking.prepend(pageHead('RANKING','Estatística de corretores','Dados derivados fora da camada de apresentação.'));
    pages.weekend.prepend(pageHead('FIM DE SEMANA','Sábado e domingo','Elegibilidade recebida pronta do domínio.'));
    pages.models.prepend(pageHead('MODEL LAB','Modelos & estatística','Champion, challengers, backtest e auditoria estatística.'));
    pages.simulation.prepend(pageHead('SIMULATION LAB','Validação por Monte Carlo','Simulação isolada da base canônica.'));
    pages.family.appendChild(familyCard(model.brokers));pages.ranking.insertBefore(topCard(model.brokers),pages.ranking.children[1]||null);pages.ranking.appendChild(recentSpecials(model.brokers));
    const wf=document.querySelector('#weekendFamily');if(wf)wf.innerHTML=(model.weekend.family||[]).map(renderWeekendStatus).join('');
    const sat=document.querySelector('#saturdayAssignments');if(sat)sat.innerHTML=(model.weekend.saturday||[]).map(x=>assignment(x,'sat')).join('');
    const sun=document.querySelector('#sundayAssignments');if(sun)sun.innerHTML=(model.weekend.sunday||[]).map(x=>assignment(x,'sun')).join('');
    const sim=document.createElement('article');sim.className='card simulation-controls';sim.innerHTML='<div class="section-head"><div><span class="eyebrow">RLT-M4-06</span><h2>Configuração da simulação</h2></div><span class="simulation-separation">SIMULATION DATA</span></div><div class="simulation-control-grid"><label><span>Universos</span><select id="simUniversesInput"><option>50</option><option selected>100</option><option>250</option><option>500</option><option>1000</option></select></label><label><span>Anos por universo</span><select id="simYearsInput"><option>1</option><option>5</option><option selected>10</option><option>20</option></select></label><label><span>Cenário</span><select id="simScenarioInput"><option value="null">NULL · acaso puro</option><option value="fixed_2x">Bias 2X · posição fixa</option><option value="morning_2x">Bias 2X · somente manhã</option><option value="high_n_2x">Bias 2X · N alto</option></select></label><label><span>Posição do sinal</span><input id="simPositionInput" type="number" min="1" value="14"></label><label><span>Força do sinal</span><select id="simStrengthInput"><option value="0.01">1%</option><option value="0.03" selected>3%</option><option value="0.05">5%</option><option value="0.10">10%</option></select></label><label id="simMinNWrap" hidden><span>N mínimo do sinal</span><input id="simMinNInput" type="number" min="4" step="1" value="25"></label><label><span>Seed</span><input id="simSeedInput" value="roleta-2026"></label><button id="runSimulation" class="simulation-run">Rodar simulação</button><button id="cancelSimulation" class="simulation-run simulation-cancel" disabled>Cancelar</button></div><div class="simulation-progress-wrap"><div class="simulation-progress"><i id="simProgressBar"></i></div><span id="simProgressText">0,0%</span></div><p id="simStatus" class="small muted">Pronto. A base real é usada somente como estrutura e estado inicial.</p><div class="simulation-audit-actions"><button id="exportSimulation" class="workspace-link-button" disabled>Exportar JSON</button><span id="simSavedRuns" class="small muted">0 runs auditáveis salvos localmente</span></div>';pages.simulation.appendChild(sim);
    const summary=document.createElement('article');summary.className='card';summary.innerHTML='<div class="section-head"><div><span class="eyebrow">ESCALA</span><h2>Universos processados</h2></div><span class="simulation-real">REAL DATA: '+model.eventModel.dataset.count+' roletas</span></div><div class="simulation-kpis"><div><span>Universos</span><strong id="simUniverses">—</strong></div><div><span>Horizonte</span><strong id="simYears">—</strong></div><div><span>Roletas sintéticas</span><strong id="simEvents">—</strong></div><div><span>Moldes estruturais</span><strong id="simTemplates">—</strong></div></div><p class="small muted">Modo: <b id="simMode">—</b> · seed: <b id="simSeedUsed">—</b></p>';pages.simulation.appendChild(summary);
    const models=document.createElement('article');models.className='card';models.innerHTML='<div class="section-head"><div><span class="eyebrow">CHAMPION vs BASELINES</span><h2>Placar Monte Carlo</h2></div><span class="muted">Top-2 congelado antes de cada sorteio</span></div><div id="simModelTable" class="sim-model-table"><div class="muted small">Rode a simulação para gerar o placar.</div></div><div class="sim-context-head"><span class="eyebrow">RLT-M4-06</span><h3>Adaptive Meta · O/E 2X</h3></div><div id="simContextTable" class="sim-context-table"><div class="muted small">Aguardando simulação.</div></div><div id="simMetaPolicy" class="sim-pairwise"><div class="muted small">Aguardando diagnóstico do meta-modelo.</div></div><div id="simPairwise" class="sim-pairwise"><div class="muted small">Aguardando comparação pareada.</div></div>';pages.simulation.appendChild(models);
    const bands=document.createElement('article');bands.className='card';bands.innerHTML='<div class="section-head"><div><span class="eyebrow">NULL LAB</span><h2>Faixa esperada sob acaso</h2></div><span class="muted">O/E 2X · P05–P95</span></div><div id="simNullBands" class="sim-band-grid"><div class="muted small">Aguardando simulação.</div></div>';pages.simulation.appendChild(bands);
    const footer=shell.querySelector('footer');if(footer)shell.appendChild(footer);
    function openPage(name){document.querySelectorAll('.workspace-page').forEach(p=>p.classList.toggle('active',p.id==='workspace-'+name));document.querySelectorAll('.workspace-nav button').forEach(b=>b.classList.toggle('active',b.dataset.workspacePage===name));window.scrollTo({top:0,behavior:'smooth'})}
    document.querySelectorAll('.workspace-nav button').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.workspacePage)));document.querySelectorAll('[data-open-workspace]').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.openWorkspace)));
  }
  global.RoletaWorkspace={mount};
})(typeof globalThis!=='undefined'?globalThis:this);
